### ISSUE TITLE
Formatting recommendation

### ISSUE THREAD

**Issue by jgbradley1** [puzzlef/leiden-communities-openmp#4]
Just a small recommendation. Would there be any opposition to adding a `.clang-format` file to this repo to autoformat the code and improve readability?

After installing [clang-format](https://clang.llvm.org/docs/ClangFormatStyleOptions.html), you can generate a default `.clang-format` file by running
```shell
clang-format -style=google -dump-config > .clang-format # choose whatever style you like
```
To apply settings to all files across the repo
```shell
find . -iname '*.hxx' -o -iname '*.cxx' | xargs clang-format -i
```

**Comment by wolfram77** [comment]
You are right, I should use a formatter for future projects - but not for this one - this is now "legacy" 😉

**Comment by jgbradley1** [comment]
Thanks for the heads up. Has this project been integrated into a new OSS project that is not legacy? Or have you just moved on to other work?

**Comment by wolfram77** [comment]
To my knowledge, it has not been integrated to an OSS project. I am currently focused on building on top of this as part of my PhD. One of them is a memory-efficient version of Leiden algorithm, which you might be interested in. https://arxiv.org/abs/2411.02268
